Create Table On_Ice (
	Player Varchar Not Null,
	Team Varchar Not Null,
	Pos Varchar Not Null,
	GP INT NOT NULL,
	TOI	DECIMAL(8,4) NOT NULL, 
	CF INT NOT NULL,	
	CA INT NOT NULL,
	CF_perc DECIMAL(4,2) NOT NULL,
	FF INT NOT NULL,
	FA INT NOT NULL,	
	FF_perc DECIMAL(4,2) NOT NULL,	
	SF INT NOT NULL,	
	SA INT NOT NULL,	
	SF_perc DECIMAL(4,2) NOT NULL,
	GF INT Not Null,
	GA INT Not Null,	
	GF_perc	DECIMAL(5,2) NOT NULL,
	xGF	DECIMAL(5,2) NOT NULL,
	xGA	DECIMAL(5,2) NOT NULL,
	xGF_perc DECIMAL(5,2) NOT NULL,
	SCF INT NOT NULL,
	SCA INT NOT NULL,
	SCF_perc DECIMAL(5,2) NOT NULL,
	HDCF INT NOT NULL,
	HDCA INT NOT NULL,
	HDCF_perc DECIMAL(5,2) NOT NULL,
	HDGF INT NOT NULL,
	HDGA INT Not NULL,
	HDGF_perc DECIMAL(5,2) NOT NULL,
	MDCF INT NOT NULL,
	MDCA INT NOT NULL,
	MDCF_perc DECIMAL(5,2) NOT NULL,
	MDGF INT NOT NULL,
	MDGA INT NOT NULL,
	MDGF_perc DECIMAL(5,2) NOT NULL,
	LDCF INT NOT NULL,
	LDCA INT NOT NULL,
	LDCF_perc DECIMAL(5,2) NOT NULL,
	LDGF INT NOT NULL,
	LDGA INT NOT NULL,
	LDGF_perc DECIMAL(5,2) NOT NULL,
	ON_SH_perc DECIMAL(5,2) NOT NULL,
	ON_SV_perc DECIMAL(5,2) NOT NULL,
	PDO DECIMAL(4,3) NOT NULL,
	OFF_Z_Start INT NOT NULL,
	NEU_Z_Start INT NOT NULL,
	Def_Z_Start INT NOT NULL,
	OTFStart INT NOT NULL,
	OffZStart_perc DECIMAL(5,2) NOT NULL,
	Off_Zone_Faceoffs INT NOT NULL,
	Neu_Zone_Faceoffs INT NOT NULL,	
	Def_Zone_Faceoffs INT NOT NULL,
	Off_Zone_Faceoff_perc DECIMAL(5,2) NOT NULL,
	PRIMARY KEY (Player)
);

Select * from on_ice;

Create Table NatStatIndv (
	Player Varchar Not Null,
	Team Varchar Not Null,
	Pos Varchar Not Null,
	GP INT NOT NULL,
	TOI	DECIMAL(8,4) NOT NULL, 
	Goals INT NOT NULL,	
	Total_Assists INT NOT NULL,
	Primary_Assist INT NOT NULL,
	Secondary_Assist INT NOT NULL,
	Total_Points INT NOT NULL,	
	Goals_Per_60 DECIMAL(4,3) NOT NULL,	
	Assists_per_60 DECIMAL(4,3) NOT NULL,	
	Pts_per_60 DECIMAL(4,3) NOT NULL,	
	IPP DECIMAL(5,2) NOT NULL,
	Shots INT NOT NULL,
	Shooting_Perc DECIMAL(5,2) NOT NULL,	
	ixG	DECIMAL(4,2) NOT NULL,
	iCF	INT NOT NULL,
	iFF	INT NOT NULL,
	iSCF INT NOT NULL,
	iHDCF INT NOT NULL,
	Rush_Attempts INT NOT NULL,
	Rebounds_Created INT NOT NULL,
	PIM	INT NOT NULL,
	Total_Penalties INT NOT NULL,
	Minor INT NOT NULL,
	Major INT NOT NULL,
	Misconduct INT NOT NULL,
	Penalties_Drawn	INT NOT NULL,
	Giveaways INT NOT NULL,
	Takeaways INT NOT NULL,
	Hits INT NOT NULL,
	Hits_Taken INT NOT NULL,
	Shots_Blocked INT NOT NULL,
	Faceoffs_Won INT NOT NULL,
	Faceoffs_Lost INT NOT NULL,
	Faceoffs_Perc DECIMAL(5,2) NOT NULL,
	PRIMARY KEY (Player)
);

Select * from natstatindv;

Select Distinct On(ce.player) ce.player, ce.team, ce.pos, ce.gp, ce.TOI, ce.cf, ce.ca, ce.cf_perc, ce.ff, ce.fa, ce.ff_perc, ce.sf, ce.sa, ce.sf_perc, ce.gf, ce.ga, ce.gf_perc, ce.xgf, ce.xga, ce.xgf_perc, na.Goals, na.Total_Assists, na.Primary_Assist, na.Secondary_Assist, na.Total_Points, na.Goals_Per_60, na.Assists_per_60, na.Pts_per_60, na.Shooting_Perc, na.ixG, na.iCF, na.iFF, na.iSCF, na.iHDCF, na.Rush_Attempts, na.Rebounds_Created, na.PIM, na.Total_Penalties, na.Minor, na.Major, na.Misconduct, na.Penalties_Drawn, na.Giveaways, na.Takeaways, na.Hits 
Into League_Stats
From on_ice as ce
Inner Join natstatindv as na ON (ce.player=na.player);

Select * from league_stats;